### PR TITLE
Fixed curly braces :)

### PR DESCRIPTION
**Pull request by Pante**

### CODE REVIEW

**Comment by Pante** [comment]
y u nu accept? 👎

**Comment by darkpolice** [comment]
Please fix your code convention. I will be closing this Merge Request for the time being :))

**Comment by Pante** [comment]
Reopening

**Comment by darkpolice** [comment]
That's not how it works, Penty

**Comment by Pante** [comment]
Or is it? ( ͡° ͜ʖ ͡°)

**Pull request closed without merging**
